### ISSUE TITLE
Wrong sender name/email in invoice/shipment email in multistore

### ISSUE THREAD

**Issue by AlexanderRakov** [sailthru/sailthru-magento2-extension#24] opened 2017-05-16 12:20 UTC
**Preconditions:**
Different email Senders configured for different websites:
Configuration > General > Store Email Addresses > Sales Representative > Sender Name/Email

**Steps to reproduce:**
Place order on not default website
Log in to the admin panel
Open the order
Invoice order
Ship order
Check your mailbox

**Actual result:**
Invoice/shipment confirmation emails send from Sender of the default website

**Expected result:**
Invoice/shipment confirmation emails send from Sender of the website the order has been placed from

The same issue if click Send Email button on order review page in admin panel.

`getSettingsVal` method of [Api.php helper](https://github.com/sailthru/sailthru-magento2-extension/blob/master/Helper/Api.php#L159) checks store/website in `request` object, but when send email from admin panel, there is no order store code/id in `request` so all configs will be taken for default store

**Comment by silverman63** [comment] 2017-05-18 18:05
Hi, @AlexanderRakov thanks for submitting this. We'll take a look into it. 

Do you have any recommendations on how to address this issue?

**Comment by silverman63** [comment] 2017-07-06 00:29
Hi @AlexanderRakov,

I'm looking into getSettingsVal now. Will create a PR when done, and comment here. However, without customizing, the sender should just be the sender chosen from the plugin's configuration.

**Comment by silverman63** [comment] 2017-07-21 23:12
It seems the root of this comes down to the same as #17, which is proper scope for config retrieval.

Duplicate of #17

**Comment by silverman63** [comment] 2017-07-21 23:13
Also, to be clear, we do not use the Magento settings for sender. Sailthru relies on Sailthru-verified senders. You can configure them at the template level in Sailthru and in the Sailthru settings of your Magento instance.

**Comment by Hajo-Magre** [comment] 2018-04-12 14:42
Seems that this is a Magento isue: https://github.com/magento/magento2/issues/11740

Read my comment for a quick fix: https://github.com/magento/magento2/issues/11740#issuecomment-380820365

**Comment by mkashif2k17** [comment] 2018-04-12 16:02
If anyone has generic solution. Please share.

Thanks,

**Comment by Hajo-Magre** [comment] 2018-04-13 07:07
The generic solution - as in "bug fix" - will be released in Magento 2.3. The quick fix I mentioned above is a workaround, but a pretty one generic imho. Or am I missing your point?

**Comment by daveyx** [comment] 2018-06-27 07:39
@Hajo-Magre this workaround does not work for me on 2.2.4

**Comment by Hajo-Magre** [comment] 2018-06-27 07:44
@daveyx still works for me on 2.2.3. Because I will probably upgrade to 2.2.3 in het next weeks, I am curious what results you are getting with the workaround. If it's not working anymore, they probably broke it even further.

**Comment by silverman63** [comment] 2018-06-27 14:55
Hi all, I'm working on some scope-related issues now. Here are the steps we're taking:

1) `getSetttingsVal` will try to resolve store ID from request params before using store manager. We're looking for request params in the following order:
* store
* order ID
* shipment ID
* website ID

2) Specifically for emails, someone found a way to spoof correct store ID at the request level. We'll be introducing this into our `TransportBuilder`. See: https://github.com/magento/magento2/issues/8117

**Comment by manojind** [comment] 2018-10-03 10:10
Just install a small module on your magneto 2.2.5 that will work 


https://github.com/manojind/magento2.2.5-email-sender

**Comment by silverman63** [comment] 2019-11-08 22:20
This should be resolved by work on our own ScopeResolver and extra redundancy check here: https://github.com/sailthru/sailthru-magento2-extension/blob/1.5.1/Mail/TransportBuilder.php#L39-L51

**Closed by silverman63** 2019-11-08 22:20 UTC
